### ISSUE TITLE
Installing Glimpse for Elmah?

### ISSUE THREAD

**Issue by KevinBurton** [stevenlauwers22/Glimpse.Elmah#5]
It is not clear what is needed to be done after installing the NuGet package Glimpse for Elmah? The package manager interface shown in the screen shots seem out of date. The online readme mentions implementing IGlimpsePlugin. Does that need to be done? Then it says:

After installing the package you still have to include the Elmah for Glimpse client side script on your pages, preferable in your main master page.

But there isn't a Glimpse folder in my project?

Would it be possible to detail a step by step process for installing?

Thank you.

**Comment by stevenlauwers22** [comment]
@KevinBurton you're totally right, the documentation is out of date. I'll give it some time in the weekend to get it up to date again.

**Comment by stevenlauwers22** [comment]
@KevinBurton I've made some changes to the readme file. Things should be more clear now.
