### ISSUE TITLE
Javascript critical error

### ISSUE THREAD

**Issue by sky3913** [stevenlauwers22/Glimpse.Elmah#6]
I have just installed Glimpse.MVC5 and Glimpse for Elmah. I've got this error when run the application, turn on the Glimpse, click the Elmah tab and then click the View on Details column

JavaScript critical error at line 3708, column 29 in http://localhost:53154/Glimpse.axd?n=glimpse_client&hash=56c44809\n\nSCRIPT1028: Expected identifier, string or number

click continue:

Unhandled exception at line 1, column 1 in http://localhost:53154/Glimpse.axd?n=glimpse_metadata&hash=56c44809&callback=glimpse.data.initMetadata

0x800a1391 - JavaScript runtime error: 'glimpse' is undefined

click continue again:

Unhandled exception at line 1, column 1 in http://localhost:53154/Glimpse.axd?n=glimpse_request&requestId=0cc7badf-54e3-4b29-ab72-2eba45060b0d&hash=56c44809&callback=glimpse.data.initData

0x800a1391 - JavaScript runtime error: 'glimpse' is undefined

Is there any workaround for this case? I'm using ASP.NET MVC 5 and IE 11. This error doesn't appear if it run on Chrome browser.

**Comment by stevenlauwers22** [comment]
Hi,

It would be very strange if this bug is related to the Glimpse Elmah plugin, since this plugin only contains server side code. Any browser specific javascript issues are probably due to an issue with glimpse itself. Maybe Nik or Anthony, the authors of Glimpse, can help you with this error.

**Comment by sky3913** [comment]
You're right, sorry for the wrong address. I'll ask this to the authors of Glimpse, thanks.
