### ISSUE TITLE
Does not work with the latest ASP MVC 5 glimpse

### ISSUE THREAD

**Issue by weedkiller** [stevenlauwers22/Glimpse.Elmah#7]
Hi, I am trying this with the current Glimpse and its not logging in the default ELMAH location.

Also, how can I log to DB, is this an option?

**Comment by stevenlauwers22** [comment]
Glimpse for Elmah is independent of MVC. So probably your Elmah is not properly configured.

I've added and MVC sample application to this repo. See this [commit ](https://github.com/stevenlauwers22/Glimpse.Elmah/commit/07562675804807e56c3e545fae068f8f14265f4f).
This application is using ASP.NET MVC 5 + the latest version of Glimpse and Glimpse.Mvc5.

Checkout the Elmah documentation to see how you can store your logs in the DB. Glimpse for Elmah is also independent of how you configure Elmah to store the logs.

**Comment by weedkiller** [comment]
ok thanks 👍 

So I thought ELMAH was straight forward, drop in your project and it starts logging, but I guess I have to check the various places for the logs
